version: "3.8"

services:
  front-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:${PORT}"
    image: ${DOCKERHUB_USERNAME}/fe-log-let:${GITHUB_SHA}
    deploy:
      resources:
        limits:
          memory: 512M
