networks:
  traefik-public:
    external: true

services:
  front-app:
    container_name: front-app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile

    image: ${DOCKERHUB_USERNAME}/fe-log-let:${GITHUB_SHA}
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front-app.rule=PathPrefix(`/app`)"
      - "traefik.http.routers.front-app.entrypoints=web"
      - "traefik.http.services.front-app.loadbalancer.server.port=${PORT}"
    expose:
      - ${PORT}

    deploy:
      resources:
        limits:
          memory: 512M
