name: Deploy to DigitalOcean Droplet
on:
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PW: ${{ secrets.DOCKERHUB_PW }}
  GITHUB_SHA: ${{ github.sha }}
  PORT: ${{ secrets.PORT }}
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  KEY: ${{ secrets.KEY }}

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PW }}

      - name: Build and tag image
        run: |
          IMAGE_NAME=${{ env.DOCKERHUB_USERNAME }}/fe-log-let:${{ env.GITHUB_SHA }}
          docker build -t $IMAGE_NAME .

      - name: Tag and Push App Image
        run: |
          IMAGE_NAME=${{ env.DOCKERHUB_USERNAME }}/fe-log-let:${{ env.GITHUB_SHA }}
          docker push $IMAGE_NAME

  deploy:
    name: Deploy to Droplet
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy docker-compose.yml file to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          source: "docker-compose.yml"
          target: "~/fe-log-let/"

      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          script: |
            cd ~/fe-log-let/  
            echo "${{ env.DOCKERHUB_PW }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin
            # Create .env on remote for Docker Compose
            cat << 'EOF' > .env
            PORT=${{ env.PORT }}
            GITHUB_SHA=${{ env.GITHUB_SHA }}
            DOCKERHUB_USERNAME=${{ env.DOCKERHUB_USERNAME }}
            EOF
            # pull latest
            docker compose pull
            # stop & remove old
            docker stop front-app || true
            docker rm   front-app || true

            # run new
            docker compose up -d
            # prune old images
            docker image prune -a -f
